name: brojac_glasova
description: This is used so you can easily count results from your survey without needing to stay whole night awake :D
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
  fonts:
    - family: LemonMilk
      fonts:
        - asset: fonts/lemonmilk.ttf
